export const ladies = {
    title: "Womens Fashion",
    image1:"src/assets/Images/1.png",
    image2:"src/assets/Images/2.png",
    image3:"src/assets/Images/3.png",
    image4:"src/assets/Images/4.png",
    image5:"src/assets/Images/5.png",
    image6:"src/assets/Images/6.png",
    image7:"src/assets/Images/7.png",
    image8:"src/assets/Images/8.png",
    price1: " 559 INR",
    price2: "459 INR",
    price3: "659 INR",
    price4: "759 INR",
    price5: "859 INR",
    price6: "959 INR",
    price7: "589 INR",
    price8: "859 INR",
}

export const men = {
     title: "Mens Fashion",
    image1:"src/assets/Mens/1.png",
    image2:"src/assets/Mens/2.png",
    image3:"src/assets/Mens/3.png",
    image4:"src/assets/Mens/4.png",
    image5:"src/assets/Mens/5.png",
    image6:"src/assets/Mens/6.png",
    image7:"src/assets/Mens/7.png",
    image8:"src/assets/Mens/8.png",
    price1: " 459 INR",
    price2: "489 INR",
    price3: "959 INR",
    price4: "579 INR",
    price5: "898 INR",
    price6: "999 INR",
    price7: "989 INR",
    price8: "458 INR",

}
export const kid = {
     title: "Kids Fashion",
    image1:"src/assets/Kids/1.png",
    image2:"src/assets/Kids/2.png",
    image3:"src/assets/Kids/3.png",
    image4:"src/assets/Kids/4.png",
    image5:"src/assets/Kids/5.png",
    image6:"src/assets/Kids/6.png",
    image7:"src/assets/Kids/7.png",
    image8:"src/assets/Kids/8.png",
    price1: " 459 INR",
    price2: "489 INR",
    price3: "559 INR",
    price4: "479 INR",
    price5: "298 INR",
    price6: "499 INR",
    price7: "389 INR",
    price8: "358 INR",

}